name: Admin

on:
  create:
  pull_request:
    types:
      - opened
    branches:
      - 'release/**'
  push:
    branches:
      - "release/**"

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update issue status labels
        uses: snowplow-incubator/labels-helper-action@v1
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
