name: Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      SONA_USER: ${{ secrets.SONA_USER }}
      SONA_PASS: ${{ secrets.SONA_PASS }}
      SONA_PGP_PASSPHRASE: ${{ secrets.SONA_PGP_PASSPHRASE }}
      SONA_PGP_SECRET: ${{ secrets.SONA_PGP_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build
        run: ./gradlew assembleRelease

      - name: Get tag and tracker version information
        id: version
        run: |
          echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/*/}
          echo "##[set-output name=TRACKER_VERSION;]$(./gradlew -q printVersion)"

      - name: Fail if version mismatch
        if: ${{ steps.version.outputs.TAG_VERSION != steps.version.outputs.TRACKER_VERSION }}
        run: |
          echo "Tag version (${{ steps.version.outputs.TAG_VERSION }}) doesn't match version in project (${{ steps.version.outputs.TRACKER_VERSION }})"
          exit 1

      - name: Publish
        run: |
          ./gradlew uploadArchives
          ./gradlew closeAndReleaseRepository
